### PR TITLE
[Lab] Lab 8

### PR DESCRIPTION
**Pull request by mmtftr**
## 📋 Planned Tasks

- Document, update if necessary, and specify the acceptance criteria for:
  - primary features, (@mmtftr @EnesBaserr) #583 
  - domain-specific features (@Cgtycolak @NazireAta ) #584 
  - API and its documentation (@EnesBaserr ) #585 
  - Testing strategy (@atakanyasar) #587 
  - Project Standards (@ozdentarikcan ) #586 
- prepare the Meeting notes for lab8 (@asligook)

### CODE REVIEW

**Comment by asligook** [comment]
I have added the Lab 8 report under the [Lab Reports](https://github.com/bounswe/bounswe2024group1/wiki/Lab-Reports) under Wiki. It includes the team discussion held during the lab hours and the Lab 8 workload distribution.

**Comment by EnesBaserr** [comment]
Worked on #585 . Added postman collection as json and readme to use it properly. Also, worked on #583 with @mmtftr to document primary features which will be implementing on during final milestone

**Comment by ozdentarikcan** [comment]
Worked on #586. In [WCAG 2.2 Accessibility Standards - Standard Checklist and Examples](https://github.com/bounswe/bounswe2024group1/wiki/WCAG-2.2-Accessibility-Standards-%E2%80%90-Checklist-and-Examples), I documented the acceptance criteria as a checklist, provided examples, and checked the completed criteria.

**Comment by mmtftr** [comment]
Worked on #586 with @EnesBaserr

**Pull request merged**
