### PR TITLE
Implemented users/{userId}/following GET endpoint 

### LINKED ISSUE #417: Implement GET users/{userId}/following
# 📌 Implement a Feature
## 🏡 Component 
- [x] Backend

## 📚 Description
A user can get followings of other users.

## 📋 Acceptance Criteria
- [x] A user can get the following list of other users.

### 📅 Deadline
- **Estimated hours of work**: 1 hours
- **Implementation Deadline:** October 20
- **Review Deadline:** October 20 

## 👁‍🗨 Reviewer
@EnesBaserr

### PR DESCRIPTION
**Pull request by Cgtycolak**
## 📋 Proposed Changes

- Implemented users/{userId}/following GET endpoint

## Related Issue
Closes #417

### CODE REVIEW

**Review by EnesBaserr — APPROVED** [review]

**Comment by atakanyasar** [comment]
We should merge it to develop branch instead of main branch

**Comment by EnesBaserr** [comment]
Good catch > We should merge it to develop branch instead of main branch

**Comment by EnesBaserr** [comment]
Good catch @atakanyasar

**Comment by EnesBaserr** [comment]
New implementation needed for that feature. Please pull from develop branch before pushing.

**Pull request closed without merging**
