### PR TITLE
Lab 5: PR

### PR DESCRIPTION
**Pull request by mmtftr**
### Documentation
- **Documentation work**:
  - [x] Wiki page WCAG 2.2 implementation documentation (Enes @enesbaserr, Çağatay @cgtycolak)
    - Added comprehensive coverage of WCAG 2.2 principles implementation
    - Documented examples for Perceivable, Operable, Understandable, and Robust principles
    - Detailed success criteria for compliance levels with focus on Level AA
### Frontend
- **Standards implementation work**: After initially performing an accessiblity benchmark on our current frontend, we found several issues to fix. After the resolution of these issues, we will have reached _WCAG 2.2 A_ certification. Issues:
  - Adding alt texts to all non-text content (images in our case). Split into multiple tasks:
    - [X] Profile (Tarik @ozdentarikcan ) [fd75ad2](https://github.com/bounswe/bounswe2024group1/pull/475/commits/fd75ad2edabf807883627fa96d67f50e89925137)
    - [X] Tag (Asli @asligook ) [36dafe0](https://github.com/bounswe/bounswe2024group1/pull/475/commits/36dafe02b183c2701ad1f4ee260e4d46045e4c9d)
  - [x] Fix color contrast issues (Nazire @NazireAta ) [[648ca5d](https://github.com/bounswe/bounswe2024group1/pull/475/commits/648ca5dadf55ab828e72784aa7e8e6b043e3be31)] 
  - [x] Fix tabbability of the UI (Efe @mmtftr)
  - [x] Add accessibility tests (Efe @mmtftr)
- **Domain-specific features work**:
  - [x] Exercism suggested questions sidebar in Question Page (Atakan @atakanyasar ) [6a5e692]

### CODE REVIEW

**Comment by EnesBaserr** [comment]
Worked on research wiki pages about WCAG 2.2 with @Cgtycolak . Related issues are #480  #479

**Comment by Cgtycolak** [comment]
Worked on research wiki pages about WCAG 2.2 with @EnesBaserr . Related issues are https://github.com/bounswe/bounswe2024group1/issues/480 https://github.com/bounswe/bounswe2024group1/issues/479

**Comment by NazireAta** [comment]
Worked on adjusting colors to meet the contrast requirements of WCAG. Related issue is #476

**Comment by asligook** [comment]
Added alt-text for the logo images in the tag page to enhance Accessibility.
Related issue : [#477 ](https://github.com/bounswe/bounswe2024group1/issues/477)

**Comment by mmtftr** [comment]
Implemented proper tabbing support for navigation purposes. Tested tabbing in the web app. (#481)
Implemented automated accessibility testing and page unit tests for all of our current pages (#482)
commit number: 0df3f23

**Comment by mmtftr** [comment]
Merging as all tasks have been completed and reviewed by team members. The PR passes all CI checks.

**Pull request merged**
