### PR TITLE
[Lab] Lab 7 PR

### PR DESCRIPTION
**Pull request by mmtftr**
## Description
This PR tracks the work done in Lab 7. A discussion was held discussing work items and their expected outcomes (specifically around the content of documentation). Then work items were assigned, and work was done by team members. All members will create their own issues and add them to this PR.

## 📋 Work Items
- ### Lab 7 Work Items
	- Planning for the demo
	  - Documenting our data population strategy (@ozdentarikcan - #517)
	  - Documenting our scenario (@NazireAta- #515)
    - Software quality plan
	  - Documenting our current software quality plan for the frontend (@mmtftr - #514 )
	  - Implementing a missing integration test for the Tag page (@asligook)
	  - Documenting our current software quality plan for the backend
	  - Implementing unit tests for API endpoint for the backend (@Cgtycolak @EnesBaserr )

- ### Milestone 2 Relevant Work
  - Implementing feedback from Milestone 1
    - Updating diagrams to remove irrelevant and incorrect sections (@NazireAta - #519 #520 #521)
  - Implemented a prerequisite for Mobile Functionality (@atakanyasar)

### CODE REVIEW

**Comment by Cgtycolak** [comment]
Unit tests are implemented https://github.com/bounswe/bounswe2024group1/pull/513 with @EnesBaserr .

**Comment by EnesBaserr** [comment]
Unit tests are implemented https://github.com/bounswe/bounswe2024group1/pull/513 with @Cgtycolak

**Comment by ozdentarikcan** [comment]
Documented [Data Population Strategy](https://github.com/bounswe/bounswe2024group1/wiki/Data-Population-Strategy), created [Lab Report 7](https://github.com/bounswe/bounswe2024group1/wiki/Lab-Report-19.11.2024) and [Meeting Notes](https://github.com/bounswe/bounswe2024group1/wiki/Meeting-Note-7). Related issue for the data population strategy is #517.

**Comment by atakanyasar** [comment]
Implemented question creation screen for mobile

**Comment by NazireAta** [comment]
Created [Presentation Scenario](https://github.com/bounswe/bounswe2024group1/wiki/Customer-Milestone-2-Presentation-Scenario). Related Issue is #515. Also, created issues regarding the feedback for milestone 1: #519 #520 #521

**Comment by asligook** [comment]
Implemented integration test for the tag page in the frontend. Related issue is #512

**Comment by mmtftr** [comment]
Created the [software testing docs](https://github.com/bounswe/bounswe2024group1/wiki/Software-Quality-Standards). Issue #514

**Pull request merged**
